#!/usr/bin/env python3


# Copyright 2014 Matthijs Kooijman <matthijs@stdin.nl>
# Copyright 2024 Stephan Enderlein (modified and fixed)
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# This script is intended to read raw packets (currently only 802.15.4
# packets prefixed by a length byte) from a serial port and output them
# in pcap format.

import os
import sys
import time
import errno
import serial
import struct
import select
import binascii
import datetime
import argparse

class Formatter:
    def __init__(self, out):
        self.out = out

    def fileno(self):
        return self.out.fileno()

    def close(self):
        self.out.close()

class PcapFormatter(Formatter):
    def write_header(self):
        self.out.write(struct.pack("=IHHiIII",
            0xa1b2c3d4,   # magic number
            2,            # major version number
            4,            # minor version number
            0,            # GMT to local correction
            0,            # accuracy of timestamps
            1024,         # max length of captured packets, in octets
            # https://www.tcpdump.org/linktypes.html
            # https://www.geeksforgeeks.org/user-dlts-protocol-table-in-wireshark/
            147,   # data link type (DLT) user specific
        ))
        self.out.flush()

    def write_packet(self, data):
        now = datetime.datetime.now()
        timestamp = int(time.mktime(now.timetuple()))

        # pcap packet record
        self.out.write(struct.pack("=IIII",
            timestamp,        # timestamp seconds
            now.microsecond,  # timestamp microseconds
            len(data),     # number of bytes of packet
            len(data),     # actual length of packet
        ))

	# pay load
        #sl=slice(len(data))
        print("write: {}".format(binascii.hexlify(data).decode()))
        self.out.write(data)

        self.out.flush()

class HumanFormatter(Formatter):
    def write_header(self):
        pass

    def write_packet(self, data):
        self.out.write(binascii.hexlify(data).decode())
        self.out.write("\n")
        self.out.flush()

def open_fifo(options, name):
    try:
        os.mkfifo(name);
    except FileExistsError:
        pass
    except:
        raise

    if not options.quiet:
        print("Waiting for fifo to be openend...")
    # This blocks until the other side of the fifo is opened
    ret = open(name, 'wb')
    print("Fifo connected")
    return ret

def setup_output(options):
    if options.fifo:
        print("Write to fifo: {}".format(options.fifo))
        return PcapFormatter(open_fifo(options, options.fifo))
    elif options.write_file:
        print("Write to file: {}".format(options.write_file))
        return PcapFormatter(open(options.write_file, 'wb'))
    else:
        print("Write to stdout")
        return HumanFormatter(sys.stdout)

def main():
    parser = argparse.ArgumentParser(description='converts packets read from a serial port into pcap format')
    parser.add_argument('port',
                        help='The serial port to read from')
    parser.add_argument('-b', '--baudrate', default=19200, type=int,
                        help='The baudrate to use for the serial port (defaults to %(default)s)')
    parser.add_argument('-q', '--quiet', action='store_true',
                        help='Do not output any informational messages')
    output = parser.add_mutually_exclusive_group()
    output.add_argument('-F', '--fifo',
                        help='Write output to a fifo instead of stdout. The fifo is created if needed and capturing does not start until the other side of the fifo is opened.')
    output.add_argument('-w', '--write-file',
                        help='Write output to a file instead of stdout')
    output.add_argument('-d', '--send-init-delay', type=int, default=2,
                        help='Wait for this many seconds between opening the serial port and sending the init string (defaults to %(default)s)')
    output.add_argument('-s', '--send-init', type=bytes, default=b'module.enable("sniffer"); sniffer.start(1);\r\n',
                        help='Send the given string over serial to enable capture mode (defaults to %(default)s)')
    output.add_argument('-r', '--read-init', type=bytes, default=b'SNIF',
                        help='Wait until the given string is read from serial before starting capture (defaults to %(default)s)')

    options = parser.parse_args();

    try:
        # timeout separates the modbus request from modbus response. a timeout of  0.001 already is sufficiant, but
        # I have set it to much smaller to still separate requests/responses for fast responsive slave devices.
        # Timout value was tested with 19200 baud.
        timeout=0.00001
        ser = serial.Serial(options.port, options.baudrate,serial.EIGHTBITS,serial.PARITY_EVEN,serial.STOPBITS_ONE,timeout)
        print("Opened {} at {}".format(options.port, options.baudrate))
        out = setup_output(options)

        print("Write pcap header to pipe")
        out.write_header()

        while True:
            do_sniff_once(options,out,ser)

        ser.close()
        out.close()
    except KeyboardInterrupt:
        pass

def do_sniff_once(options,out,ser):

    poll = select.poll()
    # Wait to read data from serial, or until the fifo is closed
    poll.register(ser, select.POLLIN)
    poll.register(out, select.POLLERR)

    while True:
        # Wait for something to do
        events = poll.poll()

        fds = [fd for (fd, evt) in events]
        if out.fileno() in fds:
            # Error on output, e.g. fifo closed on the other end
            break
        elif ser.fileno() in fds:
            # First byte is length of packet, followed by raw data bytes
            #length = ser.read()[0]
            data = ser.read(1024)
            print("LEN {}".format(len(data)))
            if len(data) > 0:
                try:
                    out.write_packet(data)
                    break
                except OSError as e:
                    # SIGPIPE indicates the fifo was closed
                    if e.errno == errno.SIGPIPE:
                        break


if __name__ == '__main__':
    main()
